name: Build on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-pr:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LaTeX and LuaLaTeX dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-extra texlive-fonts-extra texlive-luatex texlive-lang-french latexmk fonts-noto-color-emoji
          wget https://github.com/AshDevFr/latex-cookbook-template/archive/refs/tags/v2.0.0.tar.gz
          tar -xzf v2.0.0.tar.gz
          mv latex-cookbook-template-2.0.0 latex-cookbook-template
          rm -rf latex-cookbook-template/images/recipes
          rm -rf latex-cookbook-template/samples
          cp -r ./samples latex-cookbook-template
          cp -r ./images latex-cookbook-template

      - name: Build PDF
        run: |
          cd latex-cookbook-template
          chmod +x build.sh
          ./build.sh

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cookbook-pdfs-pr-${{ github.event.pull_request.number }}
          path: latex-cookbook-template/dist/*.pdf
          retention-days: 7
          if-no-files-found: error
